# Variables - Azuriom DB
DB_PWD="PASSWORD@Secret9876543210!"
DB_NAME="site"
DB_USER="azuriom"

# MYSQL Azuriom DB
mysql -e "CREATE USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PWD}';"
mysql -e "CREATE DATABASE ${DB_NAME};"
mysql -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'127.0.0.1' WITH GRANT OPTION;"