enforce_secure_profile: true
listeners:
- query_port: 25500
  motd: §r[ §2§lAltherneum§r.fr §r] §6Hub §r! §rAltherneum.fr/§2discord
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25500
  max_players: 0
  tab_size: 50
  force_default_server: false
  forced_hosts: &id006
- query_port: 25505
  motd: §r[ §2§lAltherneum§r.fr §r] §6Survie §r! §rAltherneum.fr/§2discord
  tab_list: SERVER
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - survie
  - hub
  bind_local_address: true
  host: 0.0.0.0:25505
  max_players: 0
  tab_size: 50
  force_default_server: false
  forced_hosts: *id006
- query_port: 25504
  motd: §r[ §2§lAltherneum§r.fr §r] §6Anarchie §r! §rAltherneum.fr/§2discord
  tab_list: SERVER
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - anarchie
  - hub
  bind_local_address: true
  host: 0.0.0.0:25504
  max_players: 0
  tab_size: 50
  force_default_server: false
  forced_hosts: *id006
- query_port: 25502
  motd: §r[ §2§lAltherneum§r.fr §r] §6RPG §r! §rAltherneum.fr/§2discord
  tab_list: SERVER
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - rpg
  - hub
  bind_local_address: true
  host: 0.0.0.0:25502
  max_players: 0
  tab_size: 50
  force_default_server: false
  forced_hosts: *id006
- query_port: 25503
  motd: §r[ §2§lAltherneum§r.fr §r] §6SkyBlock §r! §rAltherneum.fr/§2discord
  tab_list: SERVER
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - skyblock
  - hub
  bind_local_address: true
  host: 0.0.0.0:25503
  max_players: 0
  tab_size: 50
  force_default_server: false
  forced_hosts: *id006
- query_port: 25501
  motd: §r[ §2§lAltherneum§r.fr §r] §6Creatif §r! §rAltherneum.fr/§2discord
  tab_list: SERVER
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - creatif
  - hub
  bind_local_address: true
  host: 0.0.0.0:25501
  max_players: 0
  tab_size: 50
  force_default_server: false
  forced_hosts: *id006
- query_port: 25506
  motd: §r[ §2§lAltherneum§r.fr §r] §6OPPrison §r! §rAltherneum.fr/§2discord
  tab_list: SERVER
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - opprison
  - hub
  bind_local_address: true
  host: 0.0.0.0:25506
  max_players: 0
  tab_size: 50
  force_default_server: false
  forced_hosts: *id006
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
prevent_proxy_connections: false
ip_forward: true
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: §r[ §2§lAltherneum§r.fr §r] §6Hub §r!
    address: localhost:25560
    restricted: false
  survie:
    motd: §r[ §2§lAltherneum§r.fr §r] §6Survie §r!
    address: localhost:25565
    restricted: false
  anarchie:
    motd: §r[ §2§lAltherneum§r.fr §r] §6Anarchie §r!
    address: localhost:25564
    restricted: false
  rpg:
    motd: §r[ §2§lAltherneum§r.fr §r] §6RPG §r!
    address: localhost:25562
    restricted: false
  skyblock:
    motd: §r[ §2§lAltherneum§r.fr §r] §6SkyBlock §r!
    address: localhost:25563
    restricted: false
  creatif:
    motd: §r[ §2§lAltherneum§r.fr §r] §6Creatif §r!
    address: localhost:25561
    restricted: false
  opprison:
    motd: §r[ §2§lAltherneum§r.fr §r] §6OPPrison §r!
    address: localhost:25566
    restricted: false
