config-version = "2.8"

bind = "0.0.0.0:25500"

motd = "<#09add3>A Velocity Server"

show-max-players = 500
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = true

player-info-forwarding-mode = "MODERN"

forwarding-secret-file = "forwarding.secret"

announce-forge = false


kick-existing-players = true

ping-passthrough = "all"

sample-players-in-ping = false

enable-player-address-logging = true

[packet-limiter]
interval = 7

packets-per-second = -1

bytes-per-second = -1

decompressed-bytes-per-second = 5242880

[servers]
hub = "localhost:25560"
test = "localhost:25567"
survie = "localhost:25565"
anarchie = "localhost:25564"
rpg = "localhost:25562"
skyblock = "localhost:25563"
creatif = "localhost:25561"
opprison = "localhost:25566"

try = [
    "hub"
]

[forced-hosts]
"hub.altherneum.fr" = ["hub"]
"test.altherneum.fr" = ["test"]
"survie.altherneum.fr" = ["survie"]
"anarchie.altherneum.fr" = ["anarchie"]
"rpg.altherneum.fr" = ["rpg"]
"skyblock.altherneum.fr" = ["skyblock"]
"creatif.altherneum.fr" = ["creatif"]
"opprison.altherneum.fr" = ["opprison"]

[advanced]
compression-threshold = 256

compression-level = -1

login-ratelimit = 3000

connection-timeout = 5000

read-timeout = 30000

haproxy-protocol = false

tcp-fast-open = false

bungee-plugin-message-channel = true

show-ping-requests = false

failover-on-unexpected-server-disconnect = true

announce-proxy-commands = true

log-command-executions = true

log-player-connections = true

accepts-transfers = false

enable-reuse-port = false

command-rate-limit = 50

forward-commands-if-rate-limited = true

kick-after-rate-limited-commands = 0

tab-complete-rate-limit = 10

kick-after-rate-limited-tab-completes = 0

[query]
enabled = false

port = 25565

map = "Velocity"

show-plugins = false