#!/bin/bash

clear

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "🐧\tOS\t\t$(uname -o)\n"
printf "🖲️\tDistribution\t$DISTRIB_DESCRIPTION\n"
printf "📟\tVersion\t\t$(uname -r)\t$(uname -m)\n"

printf "\n"

printf "⌛\tUptime\t\t$(uptime -p)\n"
printf "📅\tDepuis\t\t$(uptime -s)\n"

printf "\n"

freeh=$(free -h)
freem=$(free -m)
meminfo=$(cat /proc/meminfo)
availmem="$(awk -v arcsize="0" '/^MemAvailable:/ { print $2 + 0 }' <<< "${meminfo}")"
usedmem="$(awk -v availmem="${availmem}" '/^MemTotal:/ { print $2 - availmem }' <<< "${meminfo}")"
totalmem="$(awk '/^MemTotal:/ { print $2 }' <<< "${meminfo}")"
used="$(numfmt --round=down --from-unit=1024 --to=iec <<< "${usedmem}")"
avail="$(numfmt --round=down --from-unit=1024 --to=iec <<< "${availmem}")"
total="$(numfmt --round=down --from-unit=1024 --to=iec <<< "${totalmem}")"
percentage=$(((usedmem*100 / totalmem*100) /100))

printf "💻\tCPU\t\t$(uptime | cut -d ',' -f 4-6 | sed -e 's/^[ \t]*//')\n"
printf "🧠\tRAM\t\t$used / $total : $percentage%%\n"
printf "💾\tSDA\n"
df -hl /dev/sda* | grep -v udev

printf "\n"

printf "💾\tHôte\t\t$(hostname)\n"

printf "\n"

printf "📶\tVPS\t\t$(hostname -I)\n"

printf "\n"

printf "👀\tUtilisateurs\t$(who | sort -u | wc -l)\n"
printf "➡️\tListe :\n$(who)\n"

printf "\n"

printf "/var/log/wtmp (last) :"
printf "👀\tDernières connexions\t🆗\n"
last | head

printf "\n"

printf "/var/log/btmp (lastb) :"
printf "👀\tDernières connexions\t🔴\n"
lastb | head

printf "\n"

printf "🚨\tFail2Ban\t👮\tSSHD\n"
fail2ban-client status sshd

printf "\n"

printf "🚨\tFail2Ban\t👮\tCode-Server\n"
fail2ban-client status code-server

printf "\n"

printf "🚨\tFail2Ban\t👮\tKeeweb\n"
fail2ban-client status keeweb

printf "\n"

printf "🚨\tFail2Ban\t👮\tForgejo\n"
fail2ban-client status forgejo

printf "\n"

printf "🚨\tFail2Ban\t👮\t404\n"
fail2ban-client status 404

printf "\n"

printf "🚨\tFail2Ban\t👮\t.env\n"
fail2ban-client status env

printf "\n"

printf "🚨\tFail2Ban\t👮\t400\n"
fail2ban-client status 400

printf "\n"

printf "🚨\tFail2Ban\t👮\t401\n"
fail2ban-client status 401

printf "\n"

printf "🚨\tFail2Ban\t👮\t405\n"
fail2ban-client status 405

printf "\n"

printf "🚨\tFail2Ban\t👮\t403\n"
fail2ban-client status 403

printf "\n"

printf "🚧\tServices\t\t⚡\t\t💤\n"
printf "☎️\tDiscord\t\t\t$(systemctl is-enabled discord)\t\t$(systemctl check discord)\n"

printf "\n"

printf "📩\tsendmail\t\t$(systemctl is-enabled sendmail)\t\t$(systemctl check sendmail)\n"
printf "🔐\topendkim\t\t$(systemctl is-enabled opendkim)\t\t$(systemctl check opendkim)\n"

printf "\n"

printf "🌐\tApache2\t\t\t$(systemctl is-enabled apache2)\t\t$(systemctl check apache2)\n"
printf "💿\tMySQL\t\t\t$(systemctl is-enabled mysql)\t\t$(systemctl check mysql)\n"

printf "\n"

printf "📝\tCode-Server\t\t$(systemctl is-enabled code-server@vscode)\t\t$(systemctl check code-server@vscode)\n"

printf "\n"

printf "🐋\tdocker\t\t\t$(systemctl is-enabled docker)\t\t$(systemctl check docker)\n"

printf "\n"

printf "🗃️\tforgejo\t\t\t$(systemctl is-enabled forgejo)\t\t$(systemctl check forgejo)\n"
printf "🛠️\tforgejo-runner\t\t$(systemctl is-enabled forgejo-runner)\t\t$(systemctl check forgejo-runner)\n"

printf "\n"

printf "🚫\tFail2Ban\t\t$(systemctl is-enabled fail2ban)\t\t$(systemctl check fail2ban)\n"

printf "\n"

printf "💎\tminecraft\t\t$(systemctl is-enabled minecraft)\t$(systemctl check minecraft)\n"

printf "\n"

printf "☠️\tminecraft@anarchie\t$(systemctl is-enabled minecraft@anarchie)\t$(systemctl check minecraft@anarchie)\n"
printf "🏘️\tminecraft@créatif\t$(systemctl is-enabled minecraft@creatif)\t$(systemctl check minecraft@creatif)\n"
printf "👮\tminecraft@opprison\t$(systemctl is-enabled minecraft@opprison)\t$(systemctl check minecraft@opprison)\n"
printf "⚔️\tminecraft@rpg\t\t$(systemctl is-enabled minecraft@rpg)\t$(systemctl check minecraft@rpg)\n"
printf "🚩\tminecraft@hub\t\t$(systemctl is-enabled minecraft@hub)\t\t$(systemctl check minecraft@hub)\n"
printf "🚡\tminecraft@proxy\t\t$(systemctl is-enabled minecraft@proxy)\t\t$(systemctl check minecraft@proxy)\n"
printf "🎇\tminecraft@skyblock\t$(systemctl is-enabled minecraft@skyblock)\t\t$(systemctl check minecraft@skyblock)\n"
printf "🍗\tminecraft@survie\t$(systemctl is-enabled minecraft@survie)\t\t$(systemctl check minecraft@survie)\n"

printf "\n"

printf "🚧\tminecraft@Test\t\t$(systemctl is-enabled minecraft@test)\t\t$(systemctl check minecraft@test)\n"

printf "\n"