#!/bin/bash

clear

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "🐧\tOS\t\t$(uname -o)\n"
printf "🖲️\tDistribution\t$DISTRIB_DESCRIPTION\n"
printf "📟\tVersion\t\t$(uname -r)\t$(uname -m)\n"

printf "\n"

printf "⌛\tUptime\t\t$(uptime -p)\n"
printf "📅\tDepuis\t\t$(uptime -s)\n"

printf "\n"

freeh=$(free -h)
freem=$(free -m)
meminfo=$(cat /proc/meminfo)
availmem="$(awk -v arcsize="0" '/^MemAvailable:/ { print $2 + 0 }' <<< "${meminfo}")"
usedmem="$(awk -v availmem="${availmem}" '/^MemTotal:/ { print $2 - availmem }' <<< "${meminfo}")"
totalmem="$(awk '/^MemTotal:/ { print $2 }' <<< "${meminfo}")"
used="$(numfmt --round=down --from-unit=1024 --to=iec <<< "${usedmem}")"
avail="$(numfmt --round=down --from-unit=1024 --to=iec <<< "${availmem}")"
total="$(numfmt --round=down --from-unit=1024 --to=iec <<< "${totalmem}")"
percentage=$(((usedmem*100 / totalmem*100) /100))

printf "💻\tCPU\t\t$(uptime | cut -d ',' -f 4-6 | sed -e 's/^[ \t]*//')\n"
printf "🧠\tRAM\t\t$used / $total : $percentage%%\n"
printf "💾\tSDA\n"
df -hl /dev/sda* | grep -v udev

printf "\n"

printf "💾\tHôte\t\t$(hostname)\n"

printf "\n"

printf "📶\tVPS\t\t$(hostname -I)\n"

printf "\n"

printf "👀\tUtilisateurs\t$(who | sort -u | wc -l)\n"
printf "➡️\tListe :\n$(who)\n"

printf "\n"

printf "/var/log/wtmp (last) :"
printf "👀\tDernières connexions\t🆗\n"
last | head

printf "\n"

printf "/var/log/btmp (lastb) :"
printf "👀\tDernières connexions\t🔴\n"
lastb | head

printf "\n"

printf "🚨\tFail2Ban\t👮\tSSHD\n"
fail2ban-client status sshd

printf "\n"

printf "🚨\tFail2Ban\t👮\tCode-Server\n"
fail2ban-client status code-server

printf "\n"

printf "🚧\tServices\t\t⚡\t\t💤\n"
printf "☎️\tDiscord\t\t\t$(systemctl is-enabled discord)\t\t$(systemctl check discord)\n"
printf "🌐\tApache2\t\t\t$(systemctl is-enabled apache2)\t\t$(systemctl check apache2)\n"
printf "💿\tMySQL\t\t\t$(systemctl is-enabled mysql)\t\t$(systemctl check mysql)\n"
printf "💾\tCode-Server\t\t$(systemctl is-enabled code-server@vscode)\t\t$(systemctl check code-server@vscode)\n"
printf "🚫\tFail2Ban\t\t$(systemctl is-enabled fail2ban)\t\t$(systemctl check fail2ban)\n"
printf "💎\tMinecraft\t\t$(systemctl is-enabled minecraft)\t$(systemctl check minecraft)\n"
printf "☠️\tMinecraft@Anarchie\t$(systemctl is-enabled minecraft@anarchie)\t$(systemctl check minecraft@anarchie)\n"
printf "🏘️\tMinecraft@Créatif\t$(systemctl is-enabled minecraft@creatif)\t$(systemctl check minecraft@creatif)\n"
printf "👮\tMinecraft@OPPrison\t$(systemctl is-enabled minecraft@opprison)\t$(systemctl check minecraft@opprison)\n"
printf "⚔️\tMinecraft@RPG\t\t$(systemctl is-enabled minecraft@rpg)\t$(systemctl check minecraft@rpg)\n"
printf "🚩\tMinecraft@Hub\t\t$(systemctl is-enabled minecraft@hub)\t\t$(systemctl check minecraft@hub)\n"
printf "🚡\tMinecraft@Proxy\t\t$(systemctl is-enabled minecraft@proxy)\t\t$(systemctl check minecraft@proxy)\n"
printf "🎇\tMinecraft@SkyBlock\t$(systemctl is-enabled minecraft@skyblock)\t\t$(systemctl check minecraft@skyblock)\n"
printf "🍗\tMinecraft@Survie\t$(systemctl is-enabled minecraft@survie)\t\t$(systemctl check minecraft@survie)\n"

printf "\n"